# backend/Dockerfile
FROM node:20-alpine

# Установка nodemon глобально
RUN npm install -g nodemon

# Рабочая директория в контейнере
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальной код
COPY . .

# Запускаем в режиме разработки
CMD ["nodemon", "src/server.js"]
